In [2]:
import requests
from IPython.core.display import HTML
styles = requests.get("https://raw.githubusercontent.com/Harvard-IACS/2018-CS109A/master/content/styles/cs109.css").text
HTML(styles)

import pandas as pd
import time
import numpy as np

# 1. Data Summary

First, we import the data set and take a look at it

In [15]:
house_df = pd.read_csv('data/ready_to_use_dataset.csv')
display(house_df.shape)

(10065, 20)

In [16]:
display(house_df.dtypes)

district                               object
is_incumbent                          float64
name                                   object
party                                  object
percent                               float64
state                                  object
votes                                 float64
won                                     int64
year                                    int64
first_time_elected                    float64
count_victories                         int64
unemployement_rate                    float64
is_presidential_year                  float64
president_can_be_re_elected           float64
president_party                        object
president_overall_avg_job_approval    float64
last_D_house_seats                    float64
last_R_house_seats                    float64
last_house_majority                    object
fundraising                           float64
dtype: object

Lets describe all these variables:

- won: Response variable. 1 if the candidate won, 0 otherwise
- district: Congressional districts name
- is_incumbent: Whether an incumbent is running for re-election
- name: The candidate's name
- party: The candidate's party
- percent: The percentage of votes received by the candidate
- state: The name of the state
- votes: The number of votes recieved by the candidate
- year: The year of the election.
- first_time_elected: The year of the first election won in this district by the candidate (NaN if not applicable).
- count_victories: The number of elections won in this district by the candidate
- unemployement_rate: The unemployement rate of the district (or of the country if the information was not available) for the month before the election.
- is_presidential_year: 1 if there is a presidential election this year, 0 otherwise.
- president_can_be_re_elected: Can the president stand for re-election ? 1 = Yes, 0 = No
- president_party: The president's party (R or D)
- president_overall_avg_job_approval: The presidential job approval ratings (available from Truman to Trump). Source: Gallup.
- last_D_house_seats: The number of house seats won by democrats at the last elections
- last_R_house_seats: The number of house seats won by republicans at the last elections
- last_house_majority: Which party have the majority (R or D)
- fundraising: How much money does the candidate raised for the campaign

In [17]:
display(house_df.head())

,district,is_incumbent,name,party,percent,state,votes,won,year,first_time_elected,count_victories,unemployement_rate,is_presidential_year,president_can_be_re_elected,president_party,president_overall_avg_job_approval,last_D_house_seats,last_R_house_seats,last_house_majority,fundraising
0,District 1,0.0,Ratliff Boon,D,42.1,Indiana,4281.0,1,1824,1824.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,District 1,1.0,Ratliff Boon,D,42.8,Indiana,5202.0,1,1826,1824.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,District 1,1.0,Ratliff Boon,D,52.2,Indiana,7272.0,1,1828,1824.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,District 1,0.0,John Law,D,49.1,Indiana,10868.0,0,1830,1860.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,District 1,1.0,Ratliff Boon,D,50.9,Indiana,11280.0,1,1830,1824.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
display(house_df.describe())

,is_incumbent,percent,votes,won,year,first_time_elected,count_victories,unemployement_rate,is_presidential_year,president_can_be_re_elected,president_overall_avg_job_approval,last_D_house_seats,last_R_house_seats,fundraising
count,9947.000000,10051.000000,9988.000000,10065.000000,10065.000000,5548.000000,10065.000000,9082.000000,9963.000000,9963.000000,9001.000000,9963.000000,9963.000000,2.814000e+03
mean,0.441138,50.646933,100326.312074,0.524690,1992.005067,1987.072459,2.405763,6.197060,0.484894,0.600020,0.490064,219.732611,210.654522,1.029077e+06
std,0.496548,19.975367,55450.111199,0.499415,31.182317,32.682577,3.150896,2.159983,0.499797,0.489918,0.064504,36.242347,34.708279,1.452632e+06
min,0.000000,0.000000,0.000000,0.000000,1824.000000,1824.000000,0.000000,2.700000,0.000000,0.000000,0.395000,38.000000,86.000000,-3.469651e+04
25%,0.000000,35.900000,58190.500000,0.000000,1982.000000,1974.000000,0.000000,4.500000,0.000000,0.000000,0.480000,194.000000,180.000000,7.052945e+04
50%,0.000000,50.000000,94014.000000,1.000000,2004.000000,2002.000000,1.000000,5.700000,0.000000,1.000000,0.480000,205.000000,228.000000,7.819991e+05
75%,1.000000,64.100000,136094.250000,1.000000,2012.000000,2012.000000,4.000000,7.300000,1.000000,1.000000,0.494000,253.000000,241.000000,1.440155e+06
max,1.000000,100.000000,322514.000000,1.000000,2018.000000,2018.000000,18.000000,19.000000,1.000000,1.000000,0.701000,334.000000,303.000000,3.410465e+07

Our dataset has 10065 observations and 20 predictors.